### ISSUE TITLE
Ignore language

### ISSUE THREAD

**Issue by btxtiger** [gilmarsquinelato/i18n-manager#111]
Thank's for that really great tool!

I'm having one issue: 
I always keep a file in my translations folder called "`clear-labels.json`", where I just list all translation keys from the applications without any translation (`"key": ""`). The intention was, to find missing translations by using this file as translation file, so that all translations would be replaced by an empty string and disappear, except of these these, which have not been recorded yet.
The manager recognizes this file as "language", in this case "Belarusian - be", which produces a missing error of course. 
Would it be possible to implement an ignore list or something else? Or maybe better a list of all recognized languages and checkboxes to disable/enable them inside the manager.

Another issue I found was, that if I update a JSON file outside the manager, I need to reselect the folder for getting the changes recognized.

**Comment by gilmarsquinelato** [comment]
Hi @btxtiger! Thanks!
The first issue is really annoying, I need to improve the language detection, with that, if the detection don't detect a language just ignore that file.

And the second, this tool don't have a file watcher, because this is not detected changes outside it.

**Comment by gilmarsquinelato** [comment]
Will be released in v1.6.0
Thanks for reporting this!
