### ISSUE TITLE
Further ideas

### ISSUE THREAD

**Issue by btxtiger** [gilmarsquinelato/i18n-manager#113]
1. When introducing a new language, it is quiet exhausting to select each key and press translate. Would be helpful to be able to translate all by one click. 
2. Button: "Translate empty fields" in different colors for each language to find them quicker than always reading the heading
3. Add "clear input" button, to be able to test different translations quickly

**Comment by gilmarsquinelato** [comment]
Hello @btxtiger, thanks for the ideas!
The first idea is really good!
The second idea I think that it's not so good, imagine a folder that has dozens of languages, it will be transformed into a rainbow of buttons.
And the third, I don't think that it's so helpful, maybe I didn't saw a case that it helps.

**Comment by btxtiger** [comment]
-> 2.) How about a language index number as badge?
https://material.angular.io/components/badge/overview
Maybe some even-odd styling would be enough instead of different colors.

-> 3.) In most cases I would choose English as source language for the translation. But for some reason, there can be better results by translating from another language. Of course I could go and clear the field and press the translate button again, but this is an unhandy workflow. 
Maybe a better idea is, to remove the "Translate empty fields" button, and add a "translate from language" dropdown menu, where I can select the language, that has the translation and can be used as source for this field. This way, I could quickly get different translations results by selecting another source language for this field.

**Comment by gilmarsquinelato** [comment]
About the second, I'm not seeing an advantage to have this, because every field is a language, and I think that this is enough.

And the third could be merged with the first.

Something like this: <ComboBox of languages> <Checkbox "Only Empty Fields"> <Checkbox "All translation keys">

With that, we can remove the translation buttons and put this on the top right of the window.

**Comment by btxtiger** [comment]
2) The advantage would be to find the same language field for every key much faster. In a long list of languages, it it hard to find es-VE beneath es-ES, es-CO, ... in that tiny font. Just looking for e.g. No 7 would be much easier.

3) I am not sure if that targets the issue. Maybe I misunderstood. My intention was, to make different translations comparable. Translating English->Spanish, will not have the same result in Google translator than French->Spanish. In that case, I want to be able to decide, which translation is better.

**Comment by gilmarsquinelato** [comment]
Understood about the second.

The third I don't know how to implement, that is just a clear field and translate again from other language. Do you think that a clear field button helps?

**Comment by btxtiger** [comment]
I created a short mockup here:
[https://stackblitz.com/edit/angular-lhmkuq](https://stackblitz.com/edit/angular-lhmkuq)


![image](https://user-images.githubusercontent.com/15804690/53287414-150a9c00-377c-11e9-9e30-08fd595ca0ef.png)

**Comment by gilmarsquinelato** [comment]
Great!
But what if the upper section be like this?

<img width="714" alt="captura de tela 2019-02-23 as 4 07 32 pm" src="https://user-images.githubusercontent.com/4096165/53288145-3ae86e80-3785-11e9-9c16-b430cfceb32f.png">

**Comment by btxtiger** [comment]
I expected, that it is not always fine to use the same source language for all languages. Especially when handling Chinese or Arabic, it would be helpful to choose a different source language.

How about adding an option `"ALL LANGUAGES"` inside the target language dropdown? This way, the user would still be able to translate all languages from the source language.

I'm not sure if we could combine "Translate empty fields" and the upper global translation button. 
Maybe this could be handled by a toggle-group, so you select either "Translate empty fields of this key" or "Translate empty fields of all keys".

What do you think?

![image](https://user-images.githubusercontent.com/15804690/53288542-94529c80-3789-11e9-8a9a-5ace9216f757.png)
![image](https://user-images.githubusercontent.com/15804690/53288556-cb28b280-3789-11e9-9c5a-ef83a282e3dd.png)

**Comment by gilmarsquinelato** [comment]
This is a good idea.
I liked it.

**Comment by gilmarsquinelato** [comment]
To keep the history I will develop these features in this issue.

**Comment by btxtiger** [comment]
I found that material-select has an option to select multiple entries. This way, the converter could be used more individually with fewer steps. For example:
German, Dutch -> from English
French, Spanish -> from German
![image](https://user-images.githubusercontent.com/15804690/53308046-627f2a00-389e-11e9-95fc-80ba804c3fd7.png)

**Comment by btxtiger** [comment]
What do you think, how should be existing translations be handled?
I think if they were targeted in the form, the existing translation should be kept, and not translated again.
Otherwise individual corrections would get overwritten. So the translation should only be applied, if the key does not exist or the existing string has lenght === 0

**Comment by gilmarsquinelato** [comment]
This could be a checkbox, like "Override not empty fields".

**Comment by gilmarsquinelato** [comment]
Version 1.7.0 released with these features.

**Comment by btxtiger** [comment]
Cool!
