### ISSUE TITLE
Introduce a loading icon while loading

### ISSUE THREAD

**Issue by ohager** [gilmarsquinelato/i18n-manager#122]
E ai, @gilmarsquinelato, mano!!! Como q ta?

I just started to use this for a [project](https://github.com/burst-apps-team/phoenix) and we have a bunch of files, and a bunch of translation items. So it needs some seconds to load...

Would be awesome to have a loading item.

Furthermore, is there a way to add new translation tokens? If so, I couldn't figure out how.

**Comment by gilmarsquinelato** [comment]
E aí @ohager blz mano?

Thanks for the issue, the loading indicator will be added in the status bar (bottom of the window).
To add new translation tokens just use the right click in the tree panel :D

**Comment by ohager** [comment]
I don't see any tree panel :eyes: 
![image](https://user-images.githubusercontent.com/3920663/54435555-89978180-470f-11e9-8db3-ea903f324ad8.png)

Linux - Ubuntu 18

**Comment by gilmarsquinelato** [comment]
You need to right click on an empty space or a "folder" (a json object) in the tree

**Comment by gilmarsquinelato** [comment]
As a suggestion to see all features of this tool, open the testData folder, this folder is in this repo.

**Comment by ohager** [comment]
so que nao ha empty space, bro :(

**Comment by gilmarsquinelato** [comment]
I will improve that context menu, it's a good scenario :D
Thanks!
I will release that on v1.8.1.

**Comment by ohager** [comment]
Loading icon is implemented. Thanks for ultra-fast response
