### ISSUE TITLE
Provide a feature to sync translation files.

### ISSUE THREAD

**Issue by ohager** [gilmarsquinelato/i18n-manager#124]
Spamming you, my friend.

As I don't know how to add new items, I need to add them manually in the json files. To see these recently added items, I am forced to close and reopen the app to see the updates.

Update/Sync function, or if possible, a file watcher for auto update/sync would be extremely helpful.

**Comment by gilmarsquinelato** [comment]
This feature is kind of complex to implement and the way to add new items was commented in the issue #122
