### ISSUE TITLE
Broken Layout in V1.7

### ISSUE THREAD

**Issue by ohager** [gilmarsquinelato/i18n-manager#125]
I updated to V1.7 and got this 

![image](https://user-images.githubusercontent.com/3920663/54428444-4849a680-46fc-11e9-9e31-cb6c456a6f3f.png)

Btw: electronjs is still pointing to V1.6

![image](https://user-images.githubusercontent.com/3920663/54428493-70390a00-46fc-11e9-960c-22f9d0b97860.png)

**Comment by gilmarsquinelato** [comment]
The layout was fixed and will released in the v1.8 with other features pointed in previous issues, thanks to the report and the version pointed in the electronjs is automatically retrieved from the GitHub, probably an error occurred with the site.

**Comment by ohager** [comment]
Awesome.
