### ISSUE TITLE
Empty Folder List

### ISSUE THREAD

**Issue by GeoMarkou** [gilmarsquinelato/i18n-manager#146]
I'm not able to get the program to display my translations. Is there a step I'm missing?

Actions to reproduce
1. File > Open Folder
2. Open translation directory. It contains folders: en/global.json el/global.json
3. I'm presented with a blank screen below. Right clicking the empty list and choosing Add Item or Add Folder lets me type in a name, but doesn't do anything. I've tried running as administrator.

Windows 10

![image](https://user-images.githubusercontent.com/12272970/58741955-d103f300-845e-11e9-807d-6ab1200eb51f.png)

**Comment by gilmarsquinelato** [comment]
At the current version it's only supported flat structure. Like the testData folder in the repo. I'm developing.a new version that will be capa le to read subfolders and group files based on its prefixos.

**Comment by gilmarsquinelato** [comment]
Hi @GeoMarkou, I just released the v2.0, could you test this version to check if it fits your needs?
If everything goes ok, this issue can be closed :)
Thanks!
