### ISSUE TITLE
Open a folder doesn't work

### ISSUE THREAD

**Issue by maxime-tripla** [gilmarsquinelato/i18n-manager#149]
I started the application from the source. When I try to open a folder, nothing is happening, I stay on the homescreen. I tried with the testData folder.

I'm running macOS Sierra (10.12.6) if it can help.

**Comment by gilmarsquinelato** [comment]
Hi @maxime-tripla , thanks for reporting this.
At this time I'm developing the v2 of the i18n Manager, and it will change everything.
Some of the changes will be: change from Angular to React, path reading, files grouping.
So there will be huge changes in the behaviour of reading paths.
I would like you to wait for the new version and after check if it will work.

Thanks!

**Comment by gilmarsquinelato** [comment]
Hi @maxime-tripla, just released the v2.0, can you check it if will work for you?
If everything goes ok, this issue can be closed :D
Thanks!

**Comment by maxime-tripla** [comment]
Using `yarn start`, I get a blank screen. Nothing in the console, excepted `Electron Security Warning (Insecure Content-Security-Policy)`. The DOM has an empty body.
Using `yarn build`, I get a WinPackager error (I'm on MacOS, but I assume that the app is being built for any platform).

**Comment by gilmarsquinelato** [comment]
It's weird, open the dev tools pressing Cmd+Shift+i, select the console tab and send the logs.

**Comment by maxime-tripla** [comment]
Ohhhh sorry, I feel so stupid, I found the problem: had some other projects running in parallel, probably using the same port. I stopped them and your app worked! Thanks :)
