### ISSUE TITLE
window 1903, building on window show blank app, dev mode still running fine

### ISSUE THREAD

**Issue by heroTM737** [gilmarsquinelato/i18n-manager#158]
As the title, i'm running window 1903.
My dev mode still running fine but building production give me a blank app.
I did try to download from https://electronjs.org/apps/i18n-manager and it gives me a blank app too.

**Comment by gilmarsquinelato** [comment]
Hi @heroTM737, I think that this problem is the same as #153. I'll cose this and now you can track the bug resolution in the issue #153.
