### ISSUE TITLE
Click the Related folder link but no content shows

### ISSUE THREAD

**Issue by hoginwang** [gilmarsquinelato/i18n-manager#166]
![ScreenToGif_17](https://user-images.githubusercontent.com/4257672/61269261-a41e5c00-a7d0-11e9-91b3-f9b2bcb2a00e.gif)

v2.0.5 - Windows 10 1903

**Comment by gilmarsquinelato** [comment]
@hoginwang can you send me your translations folder? To try to detect the error.

**Comment by gilmarsquinelato** [comment]
@hoginwang Thanks for providing your translations folder, I tested and everything is working fine, have you sure that the test data is in the same path (C:\Users\hogin\Documents) as show in the home screen?

**Comment by hoginwang** [comment]
@gilmarsquinelato Yes, the testData folder never move to another path.

**Comment by gilmarsquinelato** [comment]
This is strange because I tried to open from both the home screen and from the menu, and worked fine.

**Comment by gilmarsquinelato** [comment]
Hey guys, I released the [v2.0.6](https://github.com/gilmarsquinelato/i18n-manager/releases/tag/2.0.6) that allows us to open dev tools even in production mode by just adding an environment variable (ELECTRON_IS_DEV) when opening the app.
And also this version now detects if the path exists, if not it will alert and will remove the path from recent folders. This detection may help us to detect how nodeJS is getting the folder path.

**Comment by gilmarsquinelato** [comment]
@hoginwang can you check the v2.0.6 version, please? I tried on another computer and the problem didn't occur.

**Comment by gilmarsquinelato** [comment]
Due to the lack of response, I'll close this issue.
If the problem persists in future releases, please reopen this issue.
