### ISSUE TITLE
Choosing recent folder doesn't show any translations

### ISSUE THREAD

**Issue by czytelny** [gilmarsquinelato/i18n-manager#176]
Hi, I encounter following problem with new version: 

**Steps**: 
1. Open app (I had one project added in previous version) Recent folder is visible:
<img width="1136" alt="Screenshot 2019-07-22 at 22 20 22" src="https://user-images.githubusercontent.com/5399256/61662606-02ff3c00-accf-11e9-9f51-44c44c90a19d.png">

2. Click link in "Recent folder" - I don't see any translations: 
<img width="1136" alt="Screenshot 2019-07-22 at 22 21 32" src="https://user-images.githubusercontent.com/5399256/61662649-1b6f5680-accf-11e9-9933-32fda989afd3.png">

3. But when choosing File/Open folder and selecting exactly the same one as recent - it shows up (although with "Unkown Prefix" label - not sure what it means
<img width="1136" alt="Screenshot 2019-07-22 at 22 23 43" src="https://user-images.githubusercontent.com/5399256/61662797-7012d180-accf-11e9-9211-9bfad9ffe140.png">

Regards :)

**Comment by gilmarsquinelato** [comment]
Hi @czytelny, thanks for the issue with good details!
But we already have the same issue #166, I'll close this issue to prior the first opened :)

Best regards
