### ISSUE TITLE
Renaming a Key without renaming clear all the fields

### ISSUE THREAD

**Issue by tomma5o** [gilmarsquinelato/i18n-manager#189]
Hi again 😄,

Renaming a translation key without renaming for (copy/paste) and press _enter_ clear all the translated fields so forse me to quit the program without save.

If I click _esc_ the behaviour is correct

**Comment by gilmarsquinelato** [comment]
Hi @tomma5o,

I could simulate this bug, I'll arrange some time and fix it :)
Thanks for reporting!

**Comment by gilmarsquinelato** [comment]
Hi @tomma5o, the v3.0 was released!
