### ISSUE TITLE
Features requests

### ISSUE THREAD

**Issue by clementdevos** [gilmarsquinelato/i18n-manager#197]
Hey There,

Great tool !
I don't have much time to contribute to this but i'm lacking to features to be able to use it 100% efficiently

- Reload with a shortcut (couldn't find this?)
- Show untranslated keys (keys that have the same values in 2+ languages for a key)

Cheers !

**Comment by gilmarsquinelato** [comment]
Hey @clementdevos,
Thanks!

Why reload?
The second one is a good feature, I think that can be a warning counter, I will think about how to better present it on the UI.

**Comment by clementdevos** [comment]
I'm generating my i18n files with react-intl :
It scans all my declarated keys,removes the unsed ones, instanciates the new ones with the default declared message (hence the untranslated keys request).

i18n manager doesn't seem to be scanning the drives changes so when i'm generating the files, il have to quit and reopen the file which could be quicker if i could just reload with a shortcut :)

**Comment by gilmarsquinelato** [comment]
Hmm, understood, I think that a watcher could be a good thing instead of the reload feature, what do you think?

**Comment by clementdevos** [comment]
I think it's even better, if it's not too hard to implement?

**Comment by gilmarsquinelato** [comment]
Indeed it is, but I think that it's the appropriate feature to do that job 😄

**Comment by clementdevos** [comment]
I'll appreciate any of the two 😁

**Comment by gilmarsquinelato** [comment]
Issues for each feature added 😄 
As soon as I have enough time, I start to work on them

**Comment by clementdevos** [comment]
At last, a fast-responding open-source projet maintainer. Sweet ! 

👍

**Comment by gilmarsquinelato** [comment]
Thanks!
The project is relatively small with few people opening issues, so it's quite easy to answer quickly.
But as the project grows, I think that it will be more difficult to answer so quickly.

I hope that I can continue at this quality 😄

**Comment by gilmarsquinelato** [comment]
Hi @clementdevos, the v3.0 was released!

**Comment by clementdevos** [comment]
Great news, updating right now.
