### ISSUE TITLE
Changes cause restructuring of the whole arb File

### ISSUE THREAD

**Issue by sceee** [gilmarsquinelato/i18n-manager#211]
I am using the i18n Manager to edit .arb files I use in a flutter project.

Those files come generated in a specific text file formatting.

Unfortunately, when I edit a translation using the i18n Manager, the whole file gets rearranged and restructured.
This makes it really hard to diff the changes using TortoiseGitMerge.

I am even not sure if this file would still work.

When editing/translating the file using Google Transator, it's structured the same way meaning the file remains in the original structure.

**Comment by gilmarsquinelato** [comment]
Hi @sceee, thanks for reporting this issue.
The .arb files are just JSON files, so the order should not affect anything on your project.
Try to check if the keys are organized in alphabetical order.

**Comment by sceee** [comment]
@gilmarsquinelato you are correct that it's just JSON and the order should not matter but I also want to sometimes use the Google Translation Toolkit with the same files so it would be beneficial if it would not change the file structure.

**Comment by gilmarsquinelato** [comment]
@sceee, I agree with you, I'll try to look at this

**Comment by gilmarsquinelato** [comment]
Hi @sceee, the v3.0 was released fixing this issue!
