### ISSUE TITLE
“i18n Manager.app” can’t be opened because its integrity cannot be verified.

### ISSUE THREAD

**Issue by Verlikylos** [gilmarsquinelato/i18n-manager#234]
When I try to open app on MacOS i'm getting an error:

“i18n Manager.app” can’t be opened because its integrity cannot be verified.

Stackoverflow says that app needs [notarization](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/).

My MacOS version: 10.15 Beta (19A558d)

**Comment by gilmarsquinelato** [comment]
This is happening because this app don't have a certificate.
Just right click on the app icon and select open, after confirm.

**Comment by Verlikylos** [comment]
Meh, sorry for taking your time, works now. 💃
