### ISSUE TITLE
Expand / Collapse Nodes

### ISSUE THREAD

**Issue by iurikothe** [gilmarsquinelato/i18n-manager#263]
My project has a big hierarchical translation setup. And i18n-manager starts with all nodes expanded. It would be interesting to have an option to expand/collapse all nodes at once for easier navigation.

Expanded:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/161468/67725327-5b259880-f9b8-11e9-987e-c645647f9b7c.png">

Collapsed:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/161468/67725309-46e19b80-f9b8-11e9-9b7e-27dab5236857.png">

Thanks for this amazing app!

**Comment by gilmarsquinelato** [comment]
Hi @iurikothe,

Thanks for the feature request, yeah this is annoying, I'll add this in the next version.

**Comment by gilmarsquinelato** [comment]
Hi @iurikothe, the v3.0 was released!
