### ISSUE TITLE
Search also for translation values

### ISSUE THREAD

**Issue by iurikothe** [gilmarsquinelato/i18n-manager#264]
The Current Search feature only searches for the translation keys (variables). But it would be useful to search also in the values, aka translations. So one can easily find a translation that needs to be changed by searching the current translation value.

Could be interesting to have an option to search only in keys, only in values or both.

Searching for translation key (works):
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/161468/67725696-af7d4800-f9b9-11e9-991b-29c7b2187037.png">

Searching for translation value (doesn't find 'aceptar' in spanish):

<img width="314" alt="image" src="https://user-images.githubusercontent.com/161468/67725750-d5a2e800-f9b9-11e9-9481-2131ed005420.png">

**Comment by gilmarsquinelato** [comment]
Hi @iurikothe,

Good feature, I'll add in the next version.

**Comment by gilmarsquinelato** [comment]
Released in v3.0!
