### ISSUE TITLE
Show only keys with missing translations

### ISSUE THREAD

**Issue by iurikothe** [gilmarsquinelato/i18n-manager#302]
It would be very useful to have a fast way to show only the keys with missing translations.

One possible idea, simple filtering option above the keys:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/161468/70536370-4f8fca80-1b3d-11ea-920d-aaeda19d433d.png">

**Comment by gilmarsquinelato** [comment]
Hey @iurikothe , very handy feature!

I'm thinking about to put this at the bottom of the window, in the status bar, so we can put a counter of total missing translations as well.
What do you think about it?

**Comment by iurikothe** [comment]
Yeah! The footer has loads of space for that!

**Comment by matthiasp42** [comment]
Would love this feature :)
Any idea when this will be available for download?

**Comment by gilmarsquinelato** [comment]
It will be released on v3.0
I'm working on that version, but it's being hard to have time to work on it.
The version is coming to finish the development, but I'll need to have some time yet =/

**Comment by gilmarsquinelato** [comment]
Released in v3.0!
