### ISSUE TITLE
Add custom "nodes"

### ISSUE THREAD

**Issue by Androz2091** [gilmarsquinelato/i18n-manager#328]
For example, we could define in the configuration some schemas (like snippets). For example, I could define a schema like this:
Name: "Command"
Schema:
```json
{
	"description": "Command description",
    "usage": "Command usage",
    "examples": "Command examples",
	"errors": {	
	}
}
```

 And when we make a right-click on a node, we have an option (below `Add item` and `Add Node`) `Add Command`, `Add XXX`, etc... and it automatically creates items, nodes, etc... of the schema!
I see you're working on the v3. I can't wait 😊

**Comment by gilmarsquinelato** [comment]
On the v3 we'll have the option to copy and paste nodes, so you won't need snippets to do that, you can keep a node structure and, copy it and paste whatever place you want

About the v3, I'm very excited about it, like a huuuuge performance improvement, rendering times, etc.
For the tree of nodes, I'm using the same technique as VSCode, virtual scrolling. :D
