### ISSUE TITLE
Big JSON file

### ISSUE THREAD

**Issue by Androz2091** [gilmarsquinelato/i18n-manager#329]
I have a question. If I put thousands of translations in my json file, is it, as i18n manager rewrites the file each time, can my file be corrupted?

**Comment by gilmarsquinelato** [comment]
Hi @Androz2091, no worries, this tool is being used to help to translate the [Phoenix Wallet](https://github.com/burst-apps-team/phoenix) and it has thousands of translations and more the 30 languages to translate.
So, no worries about it :D
And at this time I'm working on the v3 of this tool, and it will fix the key reordering bug.
