### ISSUE TITLE
Suggestion for dangerous UX

### ISSUE THREAD

**Issue by jeremy-holt** [gilmarsquinelato/i18n-manager#333]
Could I suggest that you add a warning dialog if the user clicks the "All Keys" radio by mistake while "Overwrite not empty fields" is checked - it is sooo easy to overwrite all the translations that have been manually changed!

![image](https://user-images.githubusercontent.com/2135027/72914859-46e30480-3d37-11ea-8f5a-d08f36f2a59c.png)

https://github.com/gilmarsquinelato/i18n-manager/issues/331#issuecomment-577144624

**Comment by gilmarsquinelato** [comment]
Released in v3.0!
