### ISSUE TITLE
Suggestion - translate resx files

### ISSUE THREAD

**Issue by jeremy-holt** [gilmarsquinelato/i18n-manager#341]
Any chance of i18n working with resx files? At the moment I use ResX which works great, but it would be nice to be able to handle all my translation needs in one app.

**Comment by gilmarsquinelato** [comment]
Unfortunately, we can't because of the ResX files don't support nesting properties, and this can lead to a lot of bugs in your file if you use this.
I've considered about xml files some months ago, but I couldn't find the best solution due to this limitation of microsoft translation files

**Comment by jeremy-holt** [comment]
Thanks for the explanation
