### ISSUE TITLE
[Bug] Numeric keys breaks tool

### ISSUE THREAD

**Issue by cyptus** [gilmarsquinelato/i18n-manager#358]
Example file "en.json":

`
{
  "TYPES": {
    "10": "First",
    "15": "Second"
  }
}
`

Empty translation file "de.json":
`{}`

When opening i18n Manager and translating "en" to "de", translation is working fine first.
After saving the manager will create an array with entries from 1 to 15 (numeric keys) and fill them with null for all entries which are not in "en" file.
This results in:

`
{
  "TYPES": [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    "Erstes",
    null,
    null,
    null,
    null,
    "Zweites"
  ]
}
`

After reopning the folder with this translation file (generated by the tool), no translations or error message will show up.

**Comment by gilmarsquinelato** [comment]
Hey @cyptus 

Thanks for that bug, I'll analyse it and release on v3.0

**Comment by cyptus** [comment]
quick workaround:

when adding an entry 
`"$": "$"`
like
`{ "TYPES": { "$": "$", "10": "First", "15": "Second" } }`
the translation works!

**Comment by gilmarsquinelato** [comment]
mmh, this is weird

**Comment by gilmarsquinelato** [comment]
Hi @cyptus, the v3.0 was released fixing this issue!

**Comment by cyptus** [comment]
> Hi @cyptus, the v3.0 was released fixing this issue!

just tested it - works great! thanks! 🎉
