### ISSUE TITLE
Failed to save following file en.json

### ISSUE THREAD

**Issue by xstable** [gilmarsquinelato/i18n-manager#388]
I got this message, if I try to enter one/any english word and save: 

![image](https://user-images.githubusercontent.com/1778068/80908338-6e2a7400-8d1f-11ea-8519-db920dd5359c.png)

How to figure out, what the issue is? The Developer-Console don't show any error.

And here is the de.json-File of it. Create an en.json file, and try to traslate & saved 

```
{
  "app": {
    "name": "Meine App",
    "slogan": "Meine erste App"
  },
  "navigation": {
    "home": "Home",
    "news": "News Meldungen",
    "licenses": "Lizenzen",
    "imprint": "Impressum"
  },
  "common": {
    "back": "zurück",
    "next": "weiter"
  },
  "date": {
    "full": "date, DD.MM.YYYY"
  },
  "legal": {
    "imprint": "navigation:imprint",
    "imprint_content": "Angaben gemäß § 5 TMG\n\nMax Muster\nMusterweg\n12345 Musterstadt\nVertreten durch:\nMax Muster\nKontakt:\nTelefon: 01234-789456\nFax: 1234-56789\nE-Mail: info@suther.de\n\nUmsatzsteuer-ID:\nUmsatzsteuer-Identifikationsnummer gemäß §27a Umsatzsteuergesetz: Musterustid.\n\nWirtschafts-ID:\nMusterwirtschaftsid\nAufsichtsbehörde:\nMusteraufsicht Musterstadt\n\nVerantwortlich für den Inhalt nach § 55 Abs. 2 RStV:\nMax Muster\nMusterweg\n12345 Musterstadt",
    "legalNotice": "Datenschutz",
    "legalNotice_content": "Hier Ihre Datenschutztexte eingeben"
  },
  "example": {
    "homeScreen_text": "Dies ist ein Beispieltext für den Home-Screen",
    "newsScreen_text": "Dies ist ein Beispieltext für NEWS-Übersicht",
    "newsScreen_button": "Zu den Newsdetails",
    "newsScreenDetail_text": "Dies ist ein Beispieltext für die NEWS-Detail-Seite",
    "newsScreenDetail_buttonBack": "zurück",
    "newsScreenDetail_buttonNews": "NewsListe"
  },
  "imprint": "Angaben gemäß § 5 TMG\n\nMax Muster\nMusterweg\n12345 Musterstadt\nVertreten durch:\nMax Muster\nKontakt:\nTelefon: 01234-789456\nFax: 1234-56789\nE-Mail: max@muster.de\n\nUmsatzsteuer-ID:\nUmsatzsteuer-Identifikationsnummer gemäß §27a Umsatzsteuergesetz: Musterustid.\n\nWirtschafts-ID:\nMusterwirtschaftsid\nAufsichtsbehörde:\nMusteraufsicht Musterstadt\n\nVerantwortlich für den Inhalt nach § 55 Abs. 2 RStV:\nMax Muster\nMusterweg\n12345 Musterstadt"
}
```

**Comment by xstable** [comment]
It seems the reason is, that you need to have all the JSON-Keys at least in your Translation-File you want to translate to!!

So e.g. if I create an file "en.json" and put this inside:
```
{
  "app": {
    "name": "My App",
    "slogan": "My first App"
  },
  "common": {
    "back": "backa",
    "next": "next"
  },
  "date": {
    "full": "{{date, YYYY-MM-DD}}"
  }
}
```
I can only edit this existing Key-Value-Pairs. 
For Example, I can not edit the "legal.imprint" from de to en... if I try, I got the above described error.

**Comment by gilmarsquinelato** [comment]
Hi @xstable 

I think that this is not the problem, because i18n manager supports nested keys.
Give a look at [testData](https://github.com/gilmarsquinelato/i18n-manager/tree/development/testData) folder.
If possible, download that folder and try to simulate it on your computer.

**Comment by xstable** [comment]
I put much effort into it, to reproduce it like I described above. 
You should perfectly fine be able to reproduce it with my above description.

**Comment by xstable** [comment]
BTW: Maybe I have new Information for you. 
I rewrote the Language-File (for testing purposes) to don't use underscores anymore, because generally underscores are part of i18n-context functionality. 

So the above described issue might caused by this ?!
Hope that give you additional valuable input to solve this bug.

**Comment by gilmarsquinelato** [comment]
I know you have put much effort to simulate the bug, thanks for that.
But what I told you is that in the testData folder we have all the possible use cases, so that we can avoid such bugs.
And with that folder we already have both structures, and this bug is not happening.
If you can, do the same steps in a separate folder, check your files permissions.

**Comment by xstable** [comment]
Looks like, the above described case is one, you still miss in your testing-folder.
File-Permissions are perfectly fine. It's really only what I've described above. 100% reproducable.

**Comment by JonasKempeneers** [comment]
I'm actually having the same issue on MacOs when trying to save any node. It works fine when I am trying to save an item, just a node does not save.

This just happened with the newest version, but I updated from an earlier one. I unfortunately don't know which version I had before.

**Comment by gilmarsquinelato** [comment]
@xstable sorry, you're right
In my testData folder isn't happening and with your steps, it occurred.

I'll fix that and release a new bugfix

**Comment by gilmarsquinelato** [comment]
Found the problem, it was related to a new merging way.
Will release the bugfix in v3.0.3 this afternoon.

Sorry for the incovenience

**Comment by JonasKempeneers** [comment]
> Found the problem, it was related to a new merging way.
> Will release the bugfix in v3.0.3 this afternoon.
> 
> Sorry for the inconvenience

These things happen, thank you for creating this.

**Comment by gilmarsquinelato** [comment]
v3.0.3 released!

**Comment by xstable** [comment]
Thank you for fixing this... and at least for creating and sharing such a nice tool!
Keep on rolling with it!
