### ISSUE TITLE
[BUG] save/load freeze

### ISSUE THREAD

**Issue by Venipa** [gilmarsquinelato/i18n-manager#405]
**Describe the bug**
stuck here - not loading keys anymore after restart (restart due to freeze while saving)

**To Reproduce**
1. opening angular translations folder
2. edit...
3. save several times

**Expected behavior**
file should save/load (also maybe asynchronously?)

**Screenshots**
![image](https://user-images.githubusercontent.com/17952364/90383715-d14ad700-e080-11ea-85f2-3641aff8db70.png)
(dont mind the metadata file)
![image](https://user-images.githubusercontent.com/17952364/90383923-1838cc80-e081-11ea-9fb4-5cfdebe0b084.png)

**App version:** [e.g. 3.0.0]

**Desktop:**
 - OS: Windows 10
 - OS Version: 2004 (Build 19041.450)

**Comment by gilmarsquinelato** [comment]
Hello @Venipa 
Do you mind to zip your folder and send it to me, please? 
So I can try to reproduce the steps with your data.

**Comment by Venipa** [comment]
found the issue, something cleared the json files (empty files, no empty objects)
even then the the manager should not freeze/crash

**Comment by gilmarsquinelato** [comment]
Happy to know you found the issue, and yep, it shouldn't freeze anyway.

As a context, the app sends the data to be saved into the main thread, making it asynchronous, so electron shouldn't freeze the UI, really don't know why it's doing that =/
