### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by hoginwang** [gilmarsquinelato/i18n-manager#70]
- add add buttons to add or delete the json data key
- add a number after the date key name to show how many translations remain missing

**Comment by gilmarsquinelato** [comment]
Hello, @hoginwang thank you for the suggestions.
Related to the first suggestion, there a context menu to handle that.
And related to the second suggestion, I will add that :)

**Comment by gilmarsquinelato** [comment]
Yes, when you right click on an item in the tree, or in the tree panel.
Well, it's supposed to work.

<img width="1076" alt="captura de tela 2018-10-25 as 10 27 59" src="https://user-images.githubusercontent.com/4096165/47503522-b7535b00-d840-11e8-9f44-09349ba8b863.png">
<img width="1081" alt="captura de tela 2018-10-25 as 10 27 41" src="https://user-images.githubusercontent.com/4096165/47503523-b7535b00-d840-11e8-9b8a-0473a6f94db9.png">

**Comment by hoginwang** [comment]
> Yes, when you right click on an item in the tree, or in the tree panel.
> Well, it's supposed to work.
> 
> <img alt="captura de tela 2018-10-25 as 10 27 59" width="1076" src="https://user-images.githubusercontent.com/4096165/47503522-b7535b00-d840-11e8-9f44-09349ba8b863.png">
> 
> <img alt="captura de tela 2018-10-25 as 10 27 41" width="1081" src="https://user-images.githubusercontent.com/4096165/47503523-b7535b00-d840-11e8-9b8a-0473a6f94db9.png">

Thank you for your detailed explanation! :satisfied: But it seems not working on my Windows 10, what a pity. :sweat_smile:

**Comment by gilmarsquinelato** [comment]
The next release will be with Angular as a new renderer. 
Maybe with this new release, this error will disappear.
I'm developing the counter feature, finishing it, will be released the v1.2.0.

**Comment by gilmarsquinelato** [comment]
@hoginwang I've just published the v1.3.0, could you test that new version, please?

**Comment by hoginwang** [comment]
> @hoginwang I've just published the v1.3.0, could you test that new version, please?

![image](https://user-images.githubusercontent.com/4257672/47518699-43f02e80-d8be-11e8-8631-b10161b659ad.png)

Good to see the context menu appeared and the number of translations remain missing! :heart_eyes::thumbsup:

But only Delete in the context menu, um... If there is more actions(like add/rename/delete the item or folder) would be perfect. :satisfied:

![image](https://user-images.githubusercontent.com/4257672/47519104-5d45aa80-d8bf-11e8-8659-1011c0e71fa1.png)

Oh by the way, how about adding a link to this repository page in the Help tab? ^^

**Comment by gilmarsquinelato** [comment]
Glad to see that it's working!
The context menu is dynamic, if you right click in an item, the option now is to delete (will be added in future the option to rename). And if you right click in the folder, the option changes.

And thanks to the suggestion related to the help menu, I will add in the next release. :)

**Comment by gilmarsquinelato** [comment]
Closing this issue, and keep updated about new releases :)
