### ISSUE TITLE
 logo design

### ISSUE THREAD

**Issue by reallinfo** [gilmarsquinelato/i18n-manager#75]
Hi @gilmarsquinelato  I am trying to support open source softwares.

the logo of this repository is very general. I can create a more original and functional logo if you want. I have an idea. do you want to see?

**Comment by gilmarsquinelato** [comment]
Hello @reallinfo, I'd like to see.
Thank you for the help.

**Comment by reallinfo** [comment]
Here is my design.

![i18n](https://user-images.githubusercontent.com/36298335/47650825-7639ae80-db92-11e8-8c2c-2c06bf7ac4b8.jpg)

**Comment by gilmarsquinelato** [comment]
It's very good, congrats for your work!
It's very better than the original :)
I'd like to put it in the project

**Comment by reallinfo** [comment]
Thanks, sure! I'll send a pr as soon as possible.

**Comment by gilmarsquinelato** [comment]
Thank you!

**Comment by reallinfo** [comment]
I sent a pr. If any problem please contact me.

**Comment by gilmarsquinelato** [comment]
Thank you @reallinfo!
