### ISSUE TITLE
Problem with Google Translate API

### ISSUE THREAD

**Issue by RamyresZscan** [gilmarsquinelato/i18n-manager#97]
I found this error when I include Google API and try translate Google

![image](https://user-images.githubusercontent.com/20306607/49886874-eee28a80-fe21-11e8-8072-61bde24e499c.png)

My files are
![image](https://user-images.githubusercontent.com/20306607/49886927-1b96a200-fe22-11e8-920a-c13b8bdfe663.png)

I search on Issues closed and not found an answer.
Please, help.
Sorry about my english.

**Comment by gilmarsquinelato** [comment]
Hello @RamyresZscan, can you check if your Translate API key is really working?
The endpoint is `https://translation.googleapis.com/language/translate/v2?key=YOUR_KEY`
And the payload is
`
{
  q: 'Hello World',
  source: 'en-US',
  target: 'es-ES'
}
`

**Comment by gilmarsquinelato** [comment]
The fix for this error will be released in the v1.5.1.
Thanks!
